### ISSUE TITLE
Archival Manifest : Received an instance of PayloadTooLargeError

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/sapindale#129]
I know https://admin.canadiana.ca/archivalmanifest is being ported to the new environment, but this can hopefully help with the porting.

I had a list of 1918 AIPs that I pasted into the "a list I supply".   The listing and slug available was fine.

When I selected all, and then hit "Initiate" it generated the following error on the server side, and Sapindale exited.

```
sapindale_1  | Starting server on port 8080
sapindale_1  | _http_outgoing.js:785
sapindale_1  |       throw new ERR_INVALID_ARG_TYPE('chunk', ['string', 'Buffer'], chunk);
sapindale_1  |       ^
sapindale_1  | 
sapindale_1  | TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of PayloadTooLargeError
sapindale_1  |     at ServerResponse.end (_http_outgoing.js:785:13)
sapindale_1  |     at Polka.onError (/sapindale/node_modules/polka/index.js:22:6)
sapindale_1  |     at next (/sapindale/node_modules/polka/index.js:94:32)
sapindale_1  |     at Array.onfinished (/sapindale/node_modules/body-parser/lib/read.js:95:9)
sapindale_1  |     at listener (/sapindale/node_modules/on-finished/index.js:169:15)
sapindale_1  |     at onFinish (/sapindale/node_modules/on-finished/index.js:100:5)
sapindale_1  |     at callback (/sapindale/node_modules/ee-first/index.js:55:10)
sapindale_1  |     at IncomingMessage.onevent (/sapindale/node_modules/ee-first/index.js:93:5)
sapindale_1  |     at IncomingMessage.emit (events.js:327:22)
sapindale_1  |     at endReadableNT (internal/streams/readable.js:1327:12) {
sapindale_1  |   code: 'ERR_INVALID_ARG_TYPE'
sapindale_1  | }

```

**Comment by RussellMcOrmond** [comment]
@DivyaKrishnan26 is moving Smelting related functionality to https://github.com/crkn-rcdr/Access-Platform/tree/main/services/admin
